# Common abbreviation for git
gabbr gpull "git pull origin"
gabbr gpush "git push origin"
gabbr gs "git status -sb"
gabbr gd "git diff"
gabbr gc "git commit -m"
gabbr gca "git commit -am"
gabbr gco "git checkout"
gabbr gb "git branch"
gabbr gbd "git branch -D"
gabbr gba "git branch -a"
gabbr gco "git checkout"
gabbr gcoa "git checkout -a"
gabbr gcob "git checkout -b"
# Common abbreviation for tmux
gabbr t "tmux"
gabbr ts "tmux new -s"
gabbr ta "tmux attach -t ."
gabbr tl "tmux ls"
gabbr tk "tmux kill-session -t"
gabbr tks "tmux kill-server"
# Common abbreviation for tmuxinator
gabbr tx "tmuxinator"
gabbr txs "tmuxinator start"
gabbr txn "tmuxinator new"
# Commom abbreviation for docker
gabbr dc "docker-compose"
gabbr dcu "docker-compose up"
gabbr dcd "docker-compose down"
gabbr dcb "docker-compose build"
gabbr dcr "docker-compose run"
gabbr dce "docker-compose exec"
